apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dep1
  labels:
    app: myapp
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers: 
      - name: c1
        image: nginx